name: Sync to Deploy Repo

on:
  push:
    branches:
      - main

jobs:
  sync-to-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Push to Deploy Repo
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.DEPLOY_PAT }}
          repository: thanhhien2510kt/Beverage_Ordering_Deploy
          branch: main
          force: true


 # TRIGGER AUTOMATION TESTS
      - name: Trigger Automation Tests
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.MY_GITHUB_PAT }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/thanhhien2510kt/DWR_CICD/dispatches \
          -d '{"event_type": "run-automation-tests"}'