name: Sync to Deploy Repo

on:
  push:
    branches:
      - main

jobs:
  sync-to-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Push to Deploy Repo
        run: |
          git config --global user.name "thanhhien2510kt"
          git config --global user.email "thanhhien2510kt@users.noreply.github.com"
          git remote add deploy_repo https://${{ secrets.MY_GITHUB_PAT }}@github.com/thanhhien2510kt/Beverage_Ordering_Deploy.git
          git push deploy_repo main --force


 # TRIGGER AUTOMATION TESTS
      - name: Trigger Automation Tests
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.MY_GITHUB_PAT }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/thanhhien2510kt/DWR_CICD/dispatches \
          -d '{"event_type": "run-automation-tests"}'